name: Linter

on:
  workflow_dispatch:
  push:
    branches:
      - "**"
    paths:
      - "./dev/**"

jobs:
  prepare:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Node.js telepítése
        uses: actions/setup-node@v4
        with:
          node-version: 21.1.0

      - name: Typescript telepítése
        run: npm install typescript -g

  error-check:
    runs-on: ubuntu-latest
    needs: prepare

    steps:
      - name: Typescript hibaellenőrzés
        run: |
          cd ./dev
          tsc --noEmit

      - name: ESLint hibaellenőrzés
        run: |
          cd ./dev
          npx eslint .
